# Generated by Django 3.2.8 on 2022-02-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=200)),
                ('engine', models.IntegerField()),
                ('seat_capacity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=122)),
                ('username', models.CharField(max_length=200)),
                ('Age', models.IntegerField(blank=True)),
                ('City', models.CharField(max_length=120)),
            ],
        ),
    ]
