# Generated by Django 3.2.8 on 2022-03-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0005_alter_contact_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='ninetalefox03@gmail.com', max_length=100),
        ),
    ]
